-- File generated by the BNF Converter (bnfc 2.9.4).

-- | The abstract syntax of language numbers.

module AbsNumbers where

import Prelude (Integer)
import qualified Prelude as C (Eq, Ord, Show, Read)

data Exp
    = Plus Exp Exp
    | Sub Exp Exp
    | Times Exp Exp
    | Div Exp Exp
    | Mod Exp Exp
    | Expon Exp Exp
    | Abs Exp
    | Num Integer
    | Neg Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

