-- File generated by the BNF Converter (bnfc 2.9.4).

-- | The abstract syntax of language numbers.

module Numbers.Abs where

import Prelude (Integer)
import qualified Prelude as C (Eq, Ord, Show, Read)

data Exp = Plus Exp Exp | Times Exp Exp | Num Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

